# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-29 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20171229_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='usubpdated',
            new_name='updated',
        ),
    ]
